* Issues

** TODO 0000: Auto Version Increment                                :feature:

This is a feature that should go in the ~py~ and ~dev~ modules.

Support for:

- date versions
- major, minor, micro
- alpha
- beta
- dev
- rc

version bump only does major minor micro.


Ideas:

- PEGs
- regexes
- staged template files
- comment bounded replacements

Should pick one. I like to be deterministic and debuggable so I prefer
the templates options.

Because we are only replacing small snippets of text out of
potentially large documents I would like use the comment bounded
replacements.


** DONE 0001: Add support for different python versions via pyenv   :feature:

In the python module we want to support using different versions of
python with environments like we can in conda.

This should take two forms:

- using venv like normal but switching to the right version in pyenv
- actually making the virtualenv with pyenv

#+begin_src bash
pyenv virtualenv 2.7.17 testing-otherversion
#+end_src

The problem with the former is that not all versions of python support
venv which I am using.

So for modern development it is fine but for testing a bunch of them
it won't work.


venv works with 3.3 and above.


In the end I made it work with a patch to the pyenv-virtualenv
code. Its a little hacky but it works.

Should think about moving to something more robust like nox.

** DONE 0002: Add support for nox in py                             :feature:


Nox is a nice test runner like tox but it works like invoke. Its very
nice and works so easily (unlike tox which I alwasy have endless
problems with whenever I try it).

It even supports conda and you can save the envs for doing interactive
stuff with.

Should integrate nicely with the invoke targets so we don't end up
duplicating them all over the place.

- [X] pyenv in general integration
- [X] conda

** TODO 0003: Add docs for file targets                             :feature:

Add a feature where you can query about the current repository
structure.

First would be to just have consistency information about the
structure in the repo.

#+begin_src bash
jubeo check .
#+end_src

Or have it for specific subdirectories:

#+begin_src bash
jubeo check info
#+end_src

And it will tell you:

- if everything expected is there
- if there are any extra things that are not explicitly ignored
- if there are ignored things there
- integrate with the doit cache to tell you about those things

Also we want to have documentation for every file so can say:

#+begin_src bash
jubeo help README.org
jubeo help info
jubeo help tasks/config.py
#+end_src

And it will tell you about each thing if it knows about them.

This can be useful in any context.

** TODO 0004: add reports for passing tests

Would like to be able to have an HTML page that I can have like a big
passing tests matrix to publish that isn't part of the CI.
** TODO 0005: user modules & plugins

Now I have a directory of "plugins" where users can write their own
modules in each project.

I also am running into the issue where I want to install plugins for a
project that I don't want every project from a repo to have.

For instance it should be optional to have lxd as a module in a python
project.

I started this as "user_modules" where you can have it install
different modules not specified by the upstream repo.

This will help with maintaining repos and keeping them focused and
incremental.

I have put this feature into the python repo, but I want this to be
across all of the repos.

(perhaps there should be a single template for the ~__init__.py~ and
other such things that repos share see [[*0006: single template for `tasks/__init__.py`][0006]]).

While I am doing this though I want to rename "plugins" to user
modules since users are making them, and I want to rename
"user_modules" to plugins, since you download and plugin.

** TODO 0006: single template for `tasks/__init__.py`

This should be the same across all repos. Make it so.
    
    
